package main

import (
	"bytes"
	"errors"
	"io"
	"strings"
	"testing"

	"minibp/lib/parser"
)

type nopWriteCloser struct {
	io.Writer
}

func (n nopWriteCloser) Close() error { return nil }

func TestRunVersionFlag(t *testing.T) {
	var stdout, stderr bytes.Buffer
	err := run([]string{"-v"}, &stdout, &stderr)
	if err != nil {
		t.Fatalf("run returned error: %v", err)
	}
	if !strings.Contains(stdout.String(), "minibp version") {
		t.Fatalf("Expected version output, got: %s", stdout.String())
	}
}

func TestRunMissingInput(t *testing.T) {
	var stdout, stderr bytes.Buffer
	err := run(nil, &stdout, &stderr)
	if err == nil {
		t.Fatal("Expected missing input error")
	}
	if !strings.Contains(err.Error(), "missing input path") {
		t.Fatalf("Expected missing input path error, got: %v", err)
	}
}

func TestRunGeneratesNinjaFile(t *testing.T) {
	oldOpen := openInputFile
	oldCreate := createOutputFile
	oldParse := parseBlueprintFile
	defer func() {
		openInputFile = oldOpen
		createOutputFile = oldCreate
		parseBlueprintFile = oldParse
	}()

	var generated bytes.Buffer
	openInputFile = func(path string) (io.ReadCloser, error) {
		return io.NopCloser(strings.NewReader("")), nil
	}
	createOutputFile = func(path string) (io.WriteCloser, error) {
		return nopWriteCloser{Writer: &generated}, nil
	}
	parseBlueprintFile = func(r io.Reader, fileName string, source ...string) (*parser.File, error) {
		return &parser.File{
			Name: fileName,
			Defs: []parser.Definition{
				&parser.Module{
					Type: "python_test_host",
					Map: &parser.Map{Properties: []*parser.Property{
						{Name: "name", Value: &parser.String{Value: "smoke"}},
						{Name: "srcs", Value: &parser.List{Values: []parser.Expression{
							&parser.String{Value: "smoke_test.py"},
						}}},
					}},
				},
			},
		}, nil
	}

	var stdout, stderr bytes.Buffer
	err := run([]string{"-o", "build.ninja", "Android.bp"}, &stdout, &stderr)
	if err != nil {
		t.Fatalf("run returned error: %v", err)
	}
	if !strings.Contains(stdout.String(), "Generated build.ninja with 1 modules") {
		t.Fatalf("Expected generation summary, got: %s", stdout.String())
	}
	if !strings.Contains(generated.String(), "build smoke.test.py: python_test smoke_test.py") {
		t.Fatalf("Expected generated ninja content, got: %s", generated.String())
	}
}

func TestParseDefinitionsFromFilesAggregatesParseErrors(t *testing.T) {
	oldOpen := openInputFile
	oldParse := parseBlueprintFile
	defer func() {
		openInputFile = oldOpen
		parseBlueprintFile = oldParse
	}()

	openInputFile = func(path string) (io.ReadCloser, error) {
		return io.NopCloser(strings.NewReader("")), nil
	}
	parseBlueprintFile = func(r io.Reader, fileName string, source ...string) (*parser.File, error) {
		return nil, errors.New("bad blueprint")
	}

	_, err := parseDefinitionsFromFiles([]string{"a.bp", "b.bp"})
	if err == nil {
		t.Fatal("Expected parseDefinitionsFromFiles error")
	}
	if !strings.Contains(err.Error(), "parsing failed:") {
		t.Fatalf("Expected aggregated parse failure, got: %v", err)
	}
}
